on:
  workflow_call:
  inputs:
    max_threshold:
      description: 'The maximum numerical value for which Fibonacci will be computed.'
      required: true
      type: number
    enable_fib:
      description: 'Whether to enable posting the Fibonacci comment (true/false).'
      required: true
      type: boolean

