name: 'Fibonacci Comment On Pr'
description: 'Posts a comment on a PR with the Fibonacci of numerical values in the diff.'
inputs:
  max_threshold:
    description: 'The maximum numerical value for which Fibonacci will be computed.'
    required: true
    type: number
  enable_fib:
    description: 'Whether to enable posting the Fibonacci comment (true/false).'
    required: true
    type: boolean
runs: 
  using: 'docker' 
  image: 'ghrc.io/${{ secrets.REPOSITORY }}/fibbot:latest'
  args: 
  - ${{ inputs.enable_fib }}
  - ${{ inputs.max_threshold }}
