name: Fibonacci Comment Workflow

on:
  push:
jobs:
  fibonacci-comment:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:  
          registry: ghcr.io 
          username: ${{ secrets.REPOSITORY }}
          password: ${{ secrets.GITHUB_TOKEN}}
          
     
      - name: Run Fibonacci script
        uses: donemmanuelo/fibbot@rus
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}  
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}  
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}  # Pull request number
        with:
          max_threshold: 100
          enable_fib: true  
          # Target image to slim
      
      - name: Work around spurious network errors in curl 8.0
        run: |
          if rustc --version --verbose | grep -q '^release: 1\.7[01]\.'; then
            echo "CARGO_HTTP_MULTIPLEXING=false" >> $GITHUB_ENV
          fi
  
      - name: running  code
        run: |
          echo "Running Fibonacci script..."
          cargo run --release
      - name: build docker image
        run: |
             docker build -t ghcr.io/${{ secrets.REPOSITORY }}/fibbot:latet
      - name: Slim Docker image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
        with:
          target: ghcr.io/${{ secrets.REPOSITORY }}/fibbot:latest  # Target image to slim
          tag: slim  # Suffix for the slimmed image tag

      - name: Push slimmed Docker image
        run: |
          docker push ghcr.io/${{ secrets.REPOSITORY }}/fibbot:slim
        

          
        
