name: Fibonacci Comment Workflow

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  fibonacci-comment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.REPOSITORY }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: <your-repo>:<your-tag>
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: calling input 
        uses: octo-org/fibbot/.github/workflows/intergration.yml@main
        with:
          max_threshold: 100
          enable_fib: true
      - name: Run Fibonacci script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}  # Repository owner
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}  # Repository name
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}  # Pull request number

        run: |
          echo "Running Fibonacci script..."
          cargo run --release


