name: Fibonacci Bot

on:
  push:
.

Here is an example modification to the workflow file    branches:
      - main
  pull_request:
    branches:

```yaml
name: Fibonacci Bot

on: [push, pull:
      - main

jobs:
  build:
    runs-on: ubuntu_request]

jobs:
  build:
    runs-on: ubuntu-latest

   -latest

    steps:
    - uses: actions/checkout@v steps:
    - uses: actions/checkout@v2

    -2

    - name: Cache cargo build
      uses: actions name: Cache cargo registry
      uses: actions/cache/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock@v2
      with:
        path: ~/.cargo
        key') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build and run
      run: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock'): cargo run --bin fib
