name: Fibonacci Comment on PR

on:
  pull_request:
    branches: 
       - main
    types: [opened, synchronized]

jobs:
  fibonacci-comment:
    runs-on: ubuntu-latest
    permissions: 
       contents: read
       packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/fibonacci-comment:latest

    - name: Run Docker image
      run: |
        docker run --env TOKEN=${{ secrets.TOKEN }} \
                   --env GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }} \
                   --env GITHUB_REPOSITORY_NAME=${{ github.event.repository.name }} \
                   --env GITHUB_PULL_REQUEST_NUMBER=${{ github.event.number }} \
                   --env INPUT_MAX_THRESHOLD=1000 \
                   --env INPUT_ENABLE_FIB=true \
                   ghcr.io/${{ github.repository }}/fibonacci-comment:latest true 1000
